export { default as Hero } from './Hero/query'
export { default as Content } from './Content/query'
export { default as SpecialSectionHeading } from './SpecialSectionHeading/query'
export { default as Promo } from './Promo/query'
export { default as TitleHero } from './TitleHero/query'
export { default as FeaturedText } from './FeaturedText/query'
